import type {NextPage} from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import {Box, Container, useColorMode, Flex, Spinner} from '@chakra-ui/react';
import {Header} from '../components/header';
import Me from '../components/me';
import Work from "../components/work";

const Scene = dynamic(() => import('../components/scene'), {
	ssr: false,
	loading: () => {
		return <Spinner w={'64px'} h={'64px'} emptyColor='#F9248FB3'/>
	}
});

const Home: NextPage = () => {
	const {colorMode} = useColorMode();
	return (
		<Box w='100vw' h='100vh' bg={`${colorMode}.brand.100`}>
			<Head>
				<title>Roman Zhydyk</title>
				<meta name='description' content='Generated by create next app'/>
				<link rel='icon' href='/favicon.ico'/>
			</Head>
			<Header/>
			<Container maxW={'container.sm'} px={5}>
				<Box position={'relative'}>
					<Flex w='100%' h='40vh' justifyContent={'center'} alignItems={'center'}>
						<Scene/>
					</Flex>
					<Flex direction={'column'} w='100%' position='absolute' zIndex={5} bottom={0} pb={10}>
						<Me/>
					</Flex>
				</Box>
				<Work/>
			</Container>
		</Box>
	);
};

export default Home;